[package]
name = "disrust"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11.*"
tungstenite = {version = "*", features = ["native-tls"]}
serde_json = "*"
serde = {version = "*", features = ["derive"]}
fragile = "*"